# permissions for end users to edit dnsentries.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cloudflare-ddns-operator
    app.kubernetes.io/managed-by: kustomize
  name: dnsentry-editor-role
rules:
  - apiGroups:
      - cloudflare-ddns.mindthebig.rocks
    resources:
      - dnsentries
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - cloudflare-ddns.mindthebig.rocks
    resources:
      - dnsentries/status
    verbs:
      - get
