# permissions for end users to view dnsentries.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cloudflare-ddns-operator
    app.kubernetes.io/managed-by: kustomize
  name: dnsentry-viewer-role
rules:
- apiGroups:
  - dnsentry.mindthebig.rocks
  resources:
  - dnsentries
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dnsentry.mindthebig.rocks
  resources:
  - dnsentries/status
  verbs:
  - get
