---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - batch
  resources:
  - cronjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloudflare-ddns.mindthebig.rocks
  resources:
  - dnsentries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloudflare-ddns.mindthebig.rocks
  resources:
  - dnsentries/finalizers
  verbs:
  - update
- apiGroups:
  - cloudflare-ddns.mindthebig.rocks
  resources:
  - dnsentries/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
