apiVersion: cloudflare-ddns.mindthebig.rocks/v1
kind: DnsEntry
metadata:
  labels:
    app.kubernetes.io/name: cloudflare-ddns-operator
    app.kubernetes.io/managed-by: kustomize
  name: dnsentry-sample
spec:
  cron: "*/1 * * * *"
  items:
    - name: test-a-1.mindthebig.rocks
      proxied: true
      ttl: 120
      type: A
      zone_name: mindthebig.rocks
      keep_after_delete: false

    - name: test-a-2.mindthebig.rocks
      proxied: false
      ttl: 120
      type: A
      zone_name: mindthebig.rocks
      keep_after_delete: false
